# Generated by Django 2.2.19 on 2023-07-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_reg_form', '0002_auto_20210804_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='region',
            field=models.CharField(choices=[('ark', 'Автономна Республіка Крим'), ('vinnytsia_oblast', 'Вінницька область'), ('volyn_oblast', 'Волинська область'), ('dnipro_oblast', 'Дніпропетровська область'), ('donetsk_oblast', 'Донецька область'), ('zhytomyr_oblast', 'Житомирська область'), ('zakarpatska_oblast', 'Закарпатська область'), ('zaporizhzhia_oblast', 'Запорізька область'), ('ivanofrankivsk_oblast', 'Івано-Франківська область'), ('kyiv_oblast', 'Київська область'), ('kirovograd_oblast', 'Кіровоградська область'), ('luhansk_oblast', 'Луганська область'), ('lviv_oblast', 'Львівська область'), ('mykolaiv_oblast', 'Миколаївська область'), ('odessa_oblast', 'Одеська область'), ('poltava_oblast', 'Полтавська область'), ('rivne_oblast', 'Рівненська область'), ('sumy_oblast', 'Сумська область'), ('ternopil_oblast', 'Тернопільська область'), ('kharkiv_oblast', 'Харківська область'), ('kherson_oblast', 'Херсонська область'), ('khmelnytskyi_oblast', 'Хмельницька область'), ('cherkasy_oblast', 'Черкаська область'), ('chernivtsi_oblast', 'Чернівецька область'), ('chernihiv_oblast', 'Чернігівська область'), ('kyiv_city', 'м. Київ'), ('sevastopol_city', 'м. Севастополь'), ('other_country', 'Інша країна')], max_length=25, verbose_name='Регіон'),
        ),
    ]
